### ISSUE TITLE
Changing % chances on items.

### ISSUE THREAD

**Issue by Quinn-Aetherwood** [p4535992/foundryvtt-potion-crafting-and-gathering#2]
Hello. This is more a question on "how to" I want to change the DC or % to pull certain ingredients. Namely White Ghost Orchird seed. At 6.9% It is a bit too high to basically have a ressurection ability at hand, which could create breaking issues of non death. Is there a way to make this much MUCH rare? Thank you.

I think i have figured it out, by changing the weight in the compendia.

**Comment by p4535992** [comment]
Glad to hear that you solved it yourself.
Sorry but I was busy with something else unfortunately and saw the issue late.
