### ISSUE TITLE
[BUG] Gathering sheets for regions broken

### ISSUE THREAD

**Issue by LozoTrioxide** [p4535992/foundryvtt-potion-crafting-and-gathering#3]
**Module Version:** v0.8.1

**Describe the bug**
All of the Gathering tables for the Regions are using the wrong roll table, and once the right roll table is selected, the pictures are blank.

Some of the singular ingredient gathering tables have the same issue.

**To Reproduce**
1. Import the rolltable & the journals
2. Go to the Gathering and Harvesting journal
3. Click each Journal entry and you will see them all blank
4. right click and edit
5. Rollable table will be incorrect and images will not appear once selected
**Expected behavior**

Rolltables to be the right ones for the region/plant.
Images to appear

**Screenshots**
![Screenshot 2024-06-17 205314](https://github.com/p4535992/foundryvtt-potion-crafting-and-gathering/assets/50601395/b51986c0-14cb-4188-89fc-7b0418afec6f)

![Screenshot 2024-06-17 205454](https://github.com/p4535992/foundryvtt-potion-crafting-and-gathering/assets/50601395/725dc4a7-a7bd-4477-967c-229caf45a024)

**Browser:**
 - Edge

**Foundry Version:** 
 - 11.315
**Game System:** 
 - 3.2.1
**Additional context**
Gatherer is installed and updated & so is better rolltables

**Comment by p4535992** [comment]
Sorry for the delay i was busy with real life 0.8.2 is working now.

**Comment by LozoTrioxide** [comment]
No worries! Thank you for fixing
